/**
 * Single source of truth for everything SEO-related.
 *
 * Imported by BOTH the browser bundle (useDocumentMeta) and the Node prerender
 * script (scripts/prerender.mjs), so keep it free of browser/Node-only APIs.
 */

/** Production origin. No trailing slash. Change here and everything follows. */
export const SITE_ORIGIN = 'https://martinbogoje.com'

export const DEFAULT_LOCALE = 'hr'
export const LOCALES = ['hr', 'en', 'de', 'pl']

/** BCP-47 tags for <html lang> and og:locale. */
export const LOCALE_TAGS = {
  hr: 'hr-HR',
  en: 'en-US',
  de: 'de-DE',
  pl: 'pl-PL',
}

/** The default locale lives at "/", the rest at "/<code>/". */
export const pathForLocale = (lng) => (lng === DEFAULT_LOCALE ? '/' : `/${lng}/`)
export const urlForLocale = (lng) => `${SITE_ORIGIN}${pathForLocale(lng)}`

/**
 * Localised URL segment for project detail pages, so German visitors get
 * /de/projekte/... rather than a Croatian word in a German URL.
 * Changing any of these breaks already-indexed URLs — add a redirect if you do.
 */
export const PROJECT_SEGMENT = {
  hr: 'projekti',
  en: 'projects',
  de: 'projekte',
  pl: 'projekty',
}

export const projectsIndexPath = (lng) => `${pathForLocale(lng)}${PROJECT_SEGMENT[lng]}/`
export const projectPath = (lng, slug) => `${projectsIndexPath(lng)}${slug}/`
export const projectUrl = (lng, slug) => `${SITE_ORIGIN}${projectPath(lng, slug)}`

/**
 * Google Search Console verification token (the value of the
 * `google-site-verification` meta tag). Paste yours here and rebuild; leave
 * empty and the tag is simply omitted.
 */
export const GOOGLE_SITE_VERIFICATION = ''

/** 1200x630 social card, generated by scripts/optimize-images.mjs. */
export const OG_IMAGE = `${SITE_ORIGIN}/og-image.jpg`
export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630

export const PERSON = {
  name: 'Martin Bogoje',
  email: 'bogojemartin@gmail.com',
  locality: 'Zagreb',
  country: 'HR',
  /**
   * Profiles that prove identity to search engines. GitHub comes from the repo
   * remote. Add your LinkedIn URL here — it is the single highest-value entry
   * for a Knowledge Panel and is currently missing.
   */
  sameAs: [
    'https://github.com/MartinWeb2003',
    // 'https://www.linkedin.com/in/<your-handle>/',
  ].filter(Boolean),
}

/** Job title per locale, mirroring hero.tagline. */
const JOB_TITLE = {
  hr: 'Softverski developer',
  en: 'Software Developer',
  de: 'Softwareentwickler',
  pl: 'Programista',
}

const KNOWS_ABOUT = [
  'React',
  'JavaScript',
  'Node.js',
  'C#',
  'PostgreSQL',
  'REST API',
  'WordPress',
  'Three.js',
  'Full-stack web development',
  'UI/UX design',
]

/**
 * schema.org Person graph. Emitted as JSON-LD into every prerendered page.
 * @param {string} lng
 * @param {{title: string, description: string}} seo locale seo block
 */
export function personSchema(lng, seo) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE_ORIGIN}/#person`,
    name: PERSON.name,
    givenName: 'Martin',
    familyName: 'Bogoje',
    url: urlForLocale(lng),
    image: OG_IMAGE,
    email: `mailto:${PERSON.email}`,
    jobTitle: JOB_TITLE[lng] ?? JOB_TITLE.en,
    description: seo.description,
    address: {
      '@type': 'PostalAddress',
      addressLocality: PERSON.locality,
      addressCountry: PERSON.country,
    },
    alumniOf: {
      '@type': 'CollegeOrUniversity',
      name: 'Faculty of Electrical Engineering and Computing, University of Zagreb',
      alternateName: 'FER, Sveučilište u Zagrebu',
      sameAs: 'https://www.fer.unizg.hr/',
    },
    worksFor: {
      '@type': 'Organization',
      name: 'Ericsson Nikola Tesla',
      sameAs: 'https://www.ericsson.hr/',
    },
    knowsAbout: KNOWS_ABOUT,
    knowsLanguage: LOCALES.map((code) => ({
      '@type': 'Language',
      name: LOCALE_TAGS[code],
      alternateName: code,
    })),
    sameAs: PERSON.sameAs,
  }
}

/**
 * schema.org WebSite graph — enables sitelinks and ties the URL to the Person.
 */
export function websiteSchema(lng, seo) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_ORIGIN}/#website`,
    url: urlForLocale(lng),
    name: seo.title,
    description: seo.description,
    inLanguage: LOCALE_TAGS[lng],
    author: { '@id': `${SITE_ORIGIN}/#person` },
    publisher: { '@id': `${SITE_ORIGIN}/#person` },
  }
}

/**
 * Breadcrumb trail for a project page: Home > Projects > <Project>.
 * @param {{name: string, url: string}[]} crumbs ordered, root first
 */
export function breadcrumbSchema(crumbs) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: c.name,
      item: c.url,
    })),
  }
}

/**
 * A single delivered project, credited to the Person.
 * @param {object} project entry from src/data/projects.js
 * @param {string} lng
 * @param {{title: string, description: string}} copy localised page copy
 */
export function creativeWorkSchema(project, lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    '@id': `${projectUrl(lng, project.slug)}#work`,
    name: project.title,
    headline: copy.title,
    description: copy.description,
    url: projectUrl(lng, project.slug),
    inLanguage: LOCALE_TAGS[lng],
    dateCreated: project.year,
    creator: { '@id': `${SITE_ORIGIN}/#person` },
    author: { '@id': `${SITE_ORIGIN}/#person` },
    keywords: project.stack.join(', '),
    image: project.images.map((src) => `${SITE_ORIGIN}${src}`),
    ...(project.liveUrl ? { sameAs: project.liveUrl } : {}),
  }
}

/** A collection page listing every project, for the projects index route. */
export function collectionSchema(lng, seo, items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    url: `${SITE_ORIGIN}${projectsIndexPath(lng)}`,
    name: seo.title,
    description: seo.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    about: { '@id': `${SITE_ORIGIN}/#person` },
    mainEntity: {
      '@type': 'ItemList',
      itemListElement: items.map((p, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: p.title,
        url: projectUrl(lng, p.slug),
      })),
    },
  }
}
