/**
 * Single source of truth for everything SEO-related.
 *
 * Imported by BOTH the browser bundle (useDocumentMeta) and the Node prerender
 * script (scripts/prerender.mjs), so keep it free of browser/Node-only APIs.
 */

/** Production origin. No trailing slash. Change here and everything follows. */
export const SITE_ORIGIN = 'https://www.bogojemartin.com'

export const DEFAULT_LOCALE = 'hr'
export const LOCALES = ['hr', 'en', 'de', 'pl']

/** BCP-47 tags for <html lang> and og:locale. */
export const LOCALE_TAGS = {
  hr: 'hr-HR',
  en: 'en-US',
  de: 'de-DE',
  pl: 'pl-PL',
}

/** The default locale lives at "/", the rest at "/<code>/". */
export const pathForLocale = (lng) => (lng === DEFAULT_LOCALE ? '/' : `/${lng}/`)
export const urlForLocale = (lng) => `${SITE_ORIGIN}${pathForLocale(lng)}`

/**
 * Localised URL segment for project detail pages, so German visitors get
 * /de/projekte/... rather than a Croatian word in a German URL.
 * Changing any of these breaks already-indexed URLs — add a redirect if you do.
 */
export const PROJECT_SEGMENT = {
  hr: 'projekti',
  en: 'projects',
  de: 'projekte',
  pl: 'projekty',
}

/**
 * Localised URL segments for the standalone pages. Changing any of these
 * breaks already-indexed URLs — add a redirect if you do.
 */
export const PAGE_SEGMENT = {
  about: { hr: 'o-meni', en: 'about', de: 'ueber-mich', pl: 'o-mnie' },
  contact: { hr: 'kontakt', en: 'contact', de: 'kontakt', pl: 'kontakt' },
  privacy: {
    hr: 'politika-privatnosti',
    en: 'privacy-policy',
    de: 'datenschutz',
    pl: 'polityka-prywatnosci',
  },
  // hr/en only, like services; see SERVICE_LOCALES.
  pricing: { hr: 'cjenik', en: 'pricing' },
}

/** @param {'about'|'contact'|'privacy'} key */
export const pagePath = (key, lng) => `${pathForLocale(lng)}${PAGE_SEGMENT[key][lng]}/`
export const pageUrl = (key, lng) => `${SITE_ORIGIN}${pagePath(key, lng)}`

/**
 * Services hub segment. Only the locales listed in SERVICE_LOCALES have these
 * pages, so this map intentionally has no de/pl entries.
 */
export const SERVICES_SEGMENT = {
  hr: 'usluge',
  en: 'services',
}

export const servicesIndexPath = (lng) => `${pathForLocale(lng)}${SERVICES_SEGMENT[lng]}/`
export const servicePath = (lng, slug) => `${servicesIndexPath(lng)}${slug}/`
export const serviceUrl = (lng, slug) => `${SITE_ORIGIN}${servicePath(lng, slug)}`

/** Blog segment. hr/en only, like services; see POST_LOCALES. */
export const BLOG_SEGMENT = {
  hr: 'blog',
  en: 'blog',
}

export const blogIndexPath = (lng) => `${pathForLocale(lng)}${BLOG_SEGMENT[lng]}/`
export const postPath = (lng, slug) => `${blogIndexPath(lng)}${slug}/`
export const postUrl = (lng, slug) => `${SITE_ORIGIN}${postPath(lng, slug)}`

export const projectsIndexPath = (lng) => `${pathForLocale(lng)}${PROJECT_SEGMENT[lng]}/`
export const projectPath = (lng, slug) => `${projectsIndexPath(lng)}${slug}/`
export const projectUrl = (lng, slug) => `${SITE_ORIGIN}${projectPath(lng, slug)}`

/**
 * Google Search Console verification token (the value of the
 * `google-site-verification` meta tag). Paste yours here and rebuild; leave
 * empty and the tag is simply omitted.
 */
export const GOOGLE_SITE_VERIFICATION = ''

/** 1200x630 social card, generated by scripts/optimize-images.mjs. */
export const OG_IMAGE = `${SITE_ORIGIN}/og-image.jpg`
export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630

export const PERSON = {
  name: 'Martin Bogoje',
  email: 'bogojemartin@gmail.com',
  locality: 'Zagreb',
  country: 'HR',

  /**
   * Optional details. Each is fully wired: set a value and it appears in the
   * about page, contact page, footer and JSON-LD automatically; leave it empty
   * and it is omitted everywhere rather than rendering blank. Nothing here is
   * required for the site to build or look right.
   *
   * Currently unset by choice. If any of them is ever added, the only cost is
   * a rebuild.
   */
  phone: '', // e.g. '+385 91 234 5678'
  photo: '', // e.g. '/martin.webp' (put the file in public/)
  linkedin: '', // e.g. 'https://www.linkedin.com/in/martin-bogoje/'
  github: 'https://github.com/MartinWeb2003',

  /** Croatian business registration number, shown in the footer when set. */
  oib: '',
}

/** Identity profiles for schema.org `sameAs`; empty entries drop out. */
export const PERSON_PROFILES = [PERSON.github, PERSON.linkedin].filter(Boolean)

/** Digits-only form for `tel:` links. */
export const phoneHref = () => (PERSON.phone ? `tel:${PERSON.phone.replace(/[^\d+]/g, '')}` : '')

/**
 * Bing Webmaster Tools verification token. Same deal as the Google one:
 * paste it in, rebuild, and the meta tag appears on every page.
 */
export const BING_SITE_VERIFICATION = ''

/**
 * Cookieless analytics. Set `plausibleDomain` (or `umamiSrc` + `umamiId`) and
 * the script is injected into every prerendered page.
 *
 * Deliberately cookieless: no cookie banner is legally required, and no
 * consent script sits on the critical path hurting INP.
 */
export const ANALYTICS = {
  plausibleDomain: '', // e.g. 'bogojemartin.com'
  umamiSrc: '',
  umamiId: '',
}

/**
 * Emit LocalBusiness schema. Only switch this on if you will stand behind a
 * real address or service area — it is required for local pack eligibility but
 * a fabricated one is worse than none.
 */
export const LOCAL_BUSINESS = {
  enabled: false,
  areaServed: ['Zagreb', 'Hrvatska'],
  streetAddress: '',
  postalCode: '',
}

/** Job title per locale, mirroring hero.tagline. */
const JOB_TITLE = {
  hr: 'Softverski developer',
  en: 'Software Developer',
  de: 'Softwareentwickler',
  pl: 'Programista',
}

const KNOWS_ABOUT = [
  'React',
  'JavaScript',
  'Node.js',
  'C#',
  'PostgreSQL',
  'REST API',
  'WordPress',
  'Three.js',
  'Full-stack web development',
  'UI/UX design',
]

/**
 * schema.org Person graph. Emitted as JSON-LD into every prerendered page.
 * @param {string} lng
 * @param {{title: string, description: string}} seo locale seo block
 */
export function personSchema(lng, seo) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': `${SITE_ORIGIN}/#person`,
    name: PERSON.name,
    givenName: 'Martin',
    familyName: 'Bogoje',
    url: urlForLocale(lng),
    image: PERSON.photo ? `${SITE_ORIGIN}${PERSON.photo}` : OG_IMAGE,
    email: `mailto:${PERSON.email}`,
    ...(PERSON.phone ? { telephone: PERSON.phone } : {}),
    jobTitle: JOB_TITLE[lng] ?? JOB_TITLE.en,
    description: seo.description,
    address: {
      '@type': 'PostalAddress',
      addressLocality: PERSON.locality,
      addressCountry: PERSON.country,
      ...(LOCAL_BUSINESS.streetAddress ? { streetAddress: LOCAL_BUSINESS.streetAddress } : {}),
      ...(LOCAL_BUSINESS.postalCode ? { postalCode: LOCAL_BUSINESS.postalCode } : {}),
    },
    alumniOf: {
      '@type': 'CollegeOrUniversity',
      name: 'Faculty of Electrical Engineering and Computing, University of Zagreb',
      alternateName: 'FER, Sveučilište u Zagrebu',
      sameAs: 'https://www.fer.unizg.hr/',
    },
    worksFor: {
      '@type': 'Organization',
      name: 'Ericsson Nikola Tesla',
      sameAs: 'https://www.ericsson.hr/',
    },
    knowsAbout: KNOWS_ABOUT,
    knowsLanguage: LOCALES.map((code) => ({
      '@type': 'Language',
      name: LOCALE_TAGS[code],
      alternateName: code,
    })),
    sameAs: PERSON_PROFILES,
  }
}

/**
 * schema.org WebSite graph — enables sitelinks and ties the URL to the Person.
 */
export function websiteSchema(lng, seo) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_ORIGIN}/#website`,
    url: urlForLocale(lng),
    name: seo.title,
    description: seo.description,
    inLanguage: LOCALE_TAGS[lng],
    author: { '@id': `${SITE_ORIGIN}/#person` },
    publisher: { '@id': `${SITE_ORIGIN}/#person` },
  }
}

/**
 * Breadcrumb trail for a project page: Home > Projects > <Project>.
 * @param {{name: string, url: string}[]} crumbs ordered, root first
 */
export function breadcrumbSchema(crumbs) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: c.name,
      item: c.url,
    })),
  }
}

/**
 * A single delivered project, credited to the Person.
 * @param {object} project entry from src/data/projects.js
 * @param {string} lng
 * @param {{title: string, description: string}} copy localised page copy
 */
export function creativeWorkSchema(project, lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    '@id': `${projectUrl(lng, project.slug)}#work`,
    name: project.title,
    headline: copy.title,
    description: copy.description,
    url: projectUrl(lng, project.slug),
    inLanguage: LOCALE_TAGS[lng],
    dateCreated: project.year,
    creator: { '@id': `${SITE_ORIGIN}/#person` },
    author: { '@id': `${SITE_ORIGIN}/#person` },
    keywords: project.stack.join(', '),
    image: project.images.map((src) => `${SITE_ORIGIN}${src}`),
    ...(project.liveUrl ? { sameAs: project.liveUrl } : {}),
  }
}

/** A collection page listing every project, for the projects index route. */
export function collectionSchema(lng, seo, items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    url: `${SITE_ORIGIN}${projectsIndexPath(lng)}`,
    name: seo.title,
    description: seo.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    about: { '@id': `${SITE_ORIGIN}/#person` },
    mainEntity: {
      '@type': 'ItemList',
      itemListElement: items.map((p, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: p.title,
        url: projectUrl(lng, p.slug),
      })),
    },
  }
}

/**
 * ProfilePage wrapping the Person entity. Added by Google in 2025 specifically
 * as an E-E-A-T signal, and the about page is where it belongs.
 */
export function profilePageSchema(lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    url: pageUrl('about', lng),
    name: copy.title,
    description: copy.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    mainEntity: { '@id': `${SITE_ORIGIN}/#person` },
  }
}

export function contactPageSchema(lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ContactPage',
    url: pageUrl('contact', lng),
    name: copy.title,
    description: copy.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    mainEntity: { '@id': `${SITE_ORIGIN}/#person` },
  }
}

/** Generic page graph for anything without a more specific type (privacy). */
export function webPageSchema(lng, copy, url) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    url,
    name: copy.title,
    description: copy.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
  }
}

/**
 * LocalBusiness, emitted only when LOCAL_BUSINESS.enabled is true. Required for
 * local pack eligibility, but it must describe a real service area.
 */
export function localBusinessSchema(lng, seo) {
  if (!LOCAL_BUSINESS.enabled) return null
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${SITE_ORIGIN}/#localbusiness`,
    name: PERSON.name,
    description: seo.description,
    url: urlForLocale(lng),
    image: PERSON.photo ? `${SITE_ORIGIN}${PERSON.photo}` : OG_IMAGE,
    email: `mailto:${PERSON.email}`,
    ...(PERSON.phone ? { telephone: PERSON.phone } : {}),
    address: {
      '@type': 'PostalAddress',
      addressLocality: PERSON.locality,
      addressCountry: PERSON.country,
      ...(LOCAL_BUSINESS.streetAddress ? { streetAddress: LOCAL_BUSINESS.streetAddress } : {}),
      ...(LOCAL_BUSINESS.postalCode ? { postalCode: LOCAL_BUSINESS.postalCode } : {}),
    },
    areaServed: LOCAL_BUSINESS.areaServed.map((name) => ({ '@type': 'Place', name })),
    founder: { '@id': `${SITE_ORIGIN}/#person` },
    sameAs: PERSON_PROFILES,
  }
}

/**
 * schema.org Service for a single offering, tied back to the Person as
 * provider. `areaServed` is what makes it useful for local intent.
 *
 * @param {object} service entry from src/data/services.js
 * @param {string} lng
 * @param {{title: string, description: string, name: string}} copy
 */
export function serviceSchema(service, lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': `${serviceUrl(lng, service.slug[lng])}#service`,
    name: copy.name,
    description: copy.description,
    url: serviceUrl(lng, service.slug[lng]),
    serviceType: copy.name,
    inLanguage: LOCALE_TAGS[lng],
    provider: { '@id': `${SITE_ORIGIN}/#person` },
    areaServed: LOCAL_BUSINESS.areaServed.map((name) => ({ '@type': 'Place', name })),
    /**
     * No `offers.price`: publishing a price that is not real is worse than
     * publishing none. Add it here once there is a rate card to stand behind.
     */
  }
}

/** ItemList of every service, for the services hub page. */
export function serviceListSchema(lng, services, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    url: `${SITE_ORIGIN}${servicesIndexPath(lng)}`,
    name: copy.title,
    description: copy.description,
    inLanguage: LOCALE_TAGS[lng],
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    about: { '@id': `${SITE_ORIGIN}/#person` },
    mainEntity: {
      '@type': 'ItemList',
      itemListElement: services.map((s, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: s.name,
        url: s.url,
      })),
    },
  }
}

/**
 * schema.org BlogPosting. `author` and `publisher` both point at the Person
 * entity rather than repeating the details, which is what ties an article to a
 * known author, the signal Google's 2025 guidance leans on hardest.
 *
 * @param {object} post entry from src/data/posts.js
 * @param {string} lng
 * @param {{title: string, description: string}} copy
 */
export function blogPostingSchema(post, lng, copy) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    '@id': `${postUrl(lng, post.slug[lng])}#post`,
    headline: copy.title,
    description: copy.description,
    url: postUrl(lng, post.slug[lng]),
    mainEntityOfPage: postUrl(lng, post.slug[lng]),
    datePublished: post.date,
    dateModified: post.updated ?? post.date,
    inLanguage: LOCALE_TAGS[lng],
    image: `${SITE_ORIGIN}${post.image}`,
    keywords: post.tags.join(', '),
    author: { '@id': `${SITE_ORIGIN}/#person` },
    publisher: { '@id': `${SITE_ORIGIN}/#person` },
    isPartOf: { '@id': `${SITE_ORIGIN}${blogIndexPath(lng)}#blog` },
  }
}

/** The blog itself, listing its posts. */
export function blogSchema(lng, copy, posts) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Blog',
    '@id': `${SITE_ORIGIN}${blogIndexPath(lng)}#blog`,
    url: `${SITE_ORIGIN}${blogIndexPath(lng)}`,
    name: copy.title,
    description: copy.description,
    inLanguage: LOCALE_TAGS[lng],
    author: { '@id': `${SITE_ORIGIN}/#person` },
    publisher: { '@id': `${SITE_ORIGIN}/#person` },
    blogPost: posts.map((p) => ({
      '@type': 'BlogPosting',
      headline: p.title,
      url: p.url,
      datePublished: p.date,
    })),
  }
}
